app:
  name: "Simple Wallet"
  env: "local"

server:
  port: "8585"

database:
  main:
    driver: "mysql"
    name: "flip"
    host: "localhost"
    port: "3306"
    user: "root"
    password: "root"
    maxopen: 50
    maxidle: 10
    maxlifetime: 3