// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "simple-wallet/internal/module/wallet/domain"

	mock "github.com/stretchr/testify/mock"
)

// WalletRepositoryInterface is an autogenerated mock type for the WalletRepositoryInterface type
type WalletRepositoryInterface struct {
	mock.Mock
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *WalletRepositoryInterface) GetByUserID(ctx context.Context, userID int64) *domain.WalletEntity {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.WalletEntity
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.WalletEntity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WalletEntity)
		}
	}

	return r0
}

// GetByUserIDForLocking provides a mock function with given fields: ctx, userID
func (_m *WalletRepositoryInterface) GetByUserIDForLocking(ctx context.Context, userID int64) *domain.WalletEntity {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDForLocking")
	}

	var r0 *domain.WalletEntity
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.WalletEntity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WalletEntity)
		}
	}

	return r0
}

// Update provides a mock function with given fields: ctx, entity
func (_m *WalletRepositoryInterface) Update(ctx context.Context, entity *domain.WalletEntity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WalletEntity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepositoryInterface creates a new instance of WalletRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepositoryInterface {
	mock := &WalletRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
