// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "simple-wallet/internal/module/transaction/domain"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepositoryInterface is an autogenerated mock type for the TransactionRepositoryInterface type
type TransactionRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, entity
func (_m *TransactionRepositoryInterface) Create(ctx context.Context, entity domain.TransactionEntity) (int64, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionEntity) (int64, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionEntity) int64); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TransactionEntity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransactionRepositoryInterface) GetByID(ctx context.Context, id int64) *domain.TransactionEntity {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.TransactionEntity
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.TransactionEntity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionEntity)
		}
	}

	return r0
}

// GetByReferenceID provides a mock function with given fields: ctx, referenceID
func (_m *TransactionRepositoryInterface) GetByReferenceID(ctx context.Context, referenceID string) *domain.TransactionEntity {
	ret := _m.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReferenceID")
	}

	var r0 *domain.TransactionEntity
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TransactionEntity); ok {
		r0 = rf(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionEntity)
		}
	}

	return r0
}

// NewTransactionRepositoryInterface creates a new instance of TransactionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepositoryInterface {
	mock := &TransactionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
