// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "simple-wallet/internal/module/balance_history/domain"

	mock "github.com/stretchr/testify/mock"
)

// BalanceHistoryRepositoryInterface is an autogenerated mock type for the BalanceHistoryRepositoryInterface type
type BalanceHistoryRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, entity
func (_m *BalanceHistoryRepositoryInterface) Create(ctx context.Context, entity domain.BalanceHistoryEntity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BalanceHistoryEntity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBalanceHistoryRepositoryInterface creates a new instance of BalanceHistoryRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceHistoryRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceHistoryRepositoryInterface {
	mock := &BalanceHistoryRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
